# Generated by Django 4.2.28 on 2026-02-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nama Kelas'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom', to='akademik.teacher', verbose_name='Wali Kelas'),
        ),
    ]
