# Generated by Django 4.2.28 on 2026-02-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard_stats', 'Can view dashboard statistics'), ('view_user_stats', 'Can view user statistics'), ('view_charts', 'Can view charts')],
            },
        ),
    ]
