# Generated by Django 4.2.28 on 2026-02-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dashboardpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardpermission',
            options={'managed': False, 'permissions': [('view_dashboard_stats', 'Can view dashboard statistics'), ('view_user_stats', 'Can view user statistics'), ('view_charts', 'Can view charts'), ('view_logs', 'Can view audit logs')]},
        ),
    ]
