# Generated by Django 4.2.28 on 2026-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FazApp Portal', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portal/logos/')),
            ],
            options={
                'verbose_name': 'Site Identity',
                'verbose_name_plural': 'Site Identities',
            },
        ),
    ]
