# Generated by Django 4.2.28 on 2026-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteidentity',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='portal/favicons/'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Untuk SEO Google'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Pisahkan dengan koma', max_length=255),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
