# Generated by Django 4.2.28 on 2026-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_siteidentity_address_siteidentity_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Banner')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('image', models.ImageField(upload_to='portal/banners/', verbose_name='Foto Banner')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Link URL (CTA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
