# Generated by Django 4.2.28 on 2026-02-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
